site_name: Copilot Studio Agent Academy
site_url: https://microsoft.github.io/mcs-agent-academy/
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.tabs.link
    - toc.follow
    - content.code.copy
nav:
  - Home: index.md
  - Recruit:
      - Welcome: recruit/README.md
      - 00-Course Setup: recruit/00-course-setup/README.md
      - 01-Introduction to Agents: recruit/01-introduction-to-agents/README.md
      - 02-Copilot Studio Fundamentals: recruit/02-copilot-studio-fundamentals/README.md
      - 03-Create Declarative Agent: recruit/03-create-a-declarative-agent-for-M365Copilot/README.md
      - 04-Create a Solution: recruit/04-creating-a-solution/README.md
      - 05-Use Prebuilt Agents: recruit/05-using-prebuilt-agents/README.md
      - 06-Create Agent from Conversation: recruit/06-create-agent-from-conversation/README.md
      - 07-Add New Topic with Trigger: recruit/07-add-new-topic-with-trigger/README.md
      - 08-Add Adaptive Card: recruit/08-add-adaptive-card/README.md
      - 09-Add Agent Flow: recruit/09-add-an-agent-flow/README.md
      - 10-Add Event Triggers: recruit/10-add-event-triggers/README.md
      - 11-Publish Your Agent: recruit/11-publish-your-agent/README.md
      - 12-Understanding Licensing: recruit/12-understanding-licensing/README.md
  - Operative (Coming Soon): operative/README.md
  - Commander (Coming Soon): commander/README.md
repo_url: https://github.com/microsoft/mcs-agent-academy
repo_name: microsoft/mcs-agent-academy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
