name: 'Recruit Completion Submission Form'
description: "Submit this issue to acknowledge completion of the Copilot Studio Agent Academy Recruit path"
title: "<Name> Recruit Completion Submission"
labels:
  - recruit-completed
body:
  - type: markdown
    attributes:
      value: |
        ### IMPORTANT: Only the first 100 people to submit an issue acknowledging completion of the course will be eligible for a badge.

  - type: checkboxes
    attributes:
      label: Badge validation form
      description: In order to receive your badge, please fill out the following form - [Badge validation form](https://aka.us11.list-manage.com/subscribe?u=b3df03dd2b64a3bc8a2a200e8&id=4a558f9e2b). If you do not submit this form, you will not receive a badge. Please check this box to confirm you have submitted the badge validation form.
      options:
        - label: I verify that I have completed the badge validation form.
          required: true

  - type: checkboxes
    attributes:
      label: Curriculum Completion Validation
      description: Please check this to confirm that you have completed the Agent Academy - Recruit curriculum.
      options:
        - label: I verify that I have completed the Agent Academy - Recruit curriculum.
          required: true

  - type: checkboxes
    attributes:
      label: Solution Verification
      description: Please upload a screenshot of your final solution into the field below to confirm that you’ve completed the solution.
      options:
        - label: I verify that I have uploaded my screenshot of my final solution into the field below.
          required: true

  - type: textarea
    id: Final_solution
    attributes:
      label: Final Solution Screenshot
      description: Please upload a screenshot of your final solution here.
    validations:
      required: true

  - type: textarea
    id: learnings
    attributes:
      label: Key Learnings and Takeaways
      description: Describe what you learned. Please mention key takeaways from the Recruit path.
    validations:
      required: true

  - type: textarea
    id: challenges
    attributes:
      label: Challenges Faced
      description: Any difficulties you encountered in this path?
    validations:
      required: true

  - type: textarea
    id: final_thoughts
    attributes:
      label: Final Thoughts
      description: Any feedback on how to improve the Recruit path?
    validations:
      required: true
